import type { Metadata } from "next";

import {Header} from "@/widgets/Header";
import "@shared/styles/globals.css";
import { Inter } from "next/font/google";
import {useRouter} from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  );
}
